### ISSUE TITLE
Temporary features for hierarchy children

### ISSUE THREAD

**Issue by felix-r** [DC-analysis/dclab#123]
I'd really like to use this but get the error `NotImplementedError: Setting temporary features for hierarchy children not implemented yet!` which is pretty self explicatory. Could this maybe be pushed upwards in the priority list? 😬

**Comment by paulmueller** [comment]
Sorry, I personally don't have enough free time on my hands.

An implementation would involve

- `dclab.rtdc_dataset.fmt_hierarchy.map_indices_child2root`
- getting the root parent by iterating `RTDC_Hierarchy.hparent`
- Setting the values of the temporary feature in the root (all non-child events becom `np.nan`)

**Comment by PinkShnack** [comment]
I reckon the new `PlugInFeature` class (see #113) will be released faster than this temporary features enhancement, and seems to handle hierarchy just fine, so that might be an option for you @felix-r.

**Comment by PinkShnack** [comment]
@felix-r Let us know here if the `PlugInFeature` class is a suitable substitute for temporary features in this regard.

If `PlugInFeatures` handle hierarchy children well, then we could either:

1. leave this issue up because we want temporary features to also do this in future or
2. close the issue because we don't want temporary features to do this.
