### ISSUE TITLE
Bug: Events have principal inertia ratio <1

### ISSUE THREAD

**Issue by B-Hartmann** [DC-analysis/dclab#212]
dclab version 0.48.1
Windows 10
python 3.9.0

When plotting the principal inertia ratio for a dataset in Shape-Out 2, I noticed values below 1, which should not be there, since the principal inertia ratio calculates the ratio of major over minor axis and should be per definition invariant to rotation.

The selected event looks normal and is one of the events with principal inertia axis < 1

![grafik](https://user-images.githubusercontent.com/75362246/220598262-0a560887-b921-4176-b5ca-0c67ee6e8175.png)

**Comment by paulmueller** [comment]
The algorithm for computing the principal inertia ratio did not change recently.
So this bug probably has been there since the start.

The correlation with the position along the channel axis is interesting.

I assume the principal inertia ratio is here computed on-the-fly by dclab, correct?

**Comment by B-Hartmann** [comment]
How can I check if the principal inertia ratio is computed on the fly?
If I check the file with h5py, like so
```bash
h = h5py.File(some_rtdc_file.rtdc)
h["events"].keys()
>>> <KeysViewHDF5 ['area_msd', 'area_ratio', 'area_um', 'aspect', 'bright_avg', 'bright_sd', 'circ', 'contour', 'corr_deform', 'deform', 'fl1_area', 'fl1_max', 'fl1_pos', 'fl1_width', 'fl2_area', 'fl2_max', 'fl2_pos', 'fl2_width', 'fl3_area', 'fl3_max', 'fl3_pos', 'fl3_width', 'frame', 'image', 'index', 'index_online', 'inert_ratio_cvx', 'inert_ratio_raw', 'mask', 'pos_x', 'pos_y', 'size_x', 'size_y', 'temp', 'time', 'trace', 'volume']>
```
I don't see `inert_ratio_prnc` there.

**Comment by B-Hartmann** [comment]
The correlation with the position along the channel axis is interesting indeed. Also visible in other datasets:

![grafik](https://user-images.githubusercontent.com/75362246/220851045-a2870e58-2ed4-4bba-a35a-f99ff3c1dd6a.png)

![grafik](https://user-images.githubusercontent.com/75362246/220851179-ee414a47-cadb-4b5e-8ea9-cb21a4a7c77b.png)

**Comment by paulmueller** [comment]
Do you have an example dataset I can take a look at? This does not appear to happen for normal datasets with short image widths.

**Comment by B-Hartmann** [comment]
Yes, the region of interest is quite long. I attached an example file with 300 events.
[example_file_dclab_issue_212.zip](https://github.com/DC-analysis/dclab/files/10812571/example_file_dclab_issue_212.zip)

**Comment by B-Hartmann** [comment]
I don't think the position matters:  
I created a new file only with events with principal inertia ratio <1, then modified the file with h5py basically subtracting 200 from all position_x values and then checked the principal inertia ratio again. The plot looks basically the same.

Code:
```Python
import dclab
import h5py

ds_filtered = dclab.new_dataset("input_data.rtdc")
ds_filtered.config["filtering"]["inert_ratio_prnc min"] = 0
ds_filtered.config["filtering"]["inert_ratio_prnc max"] = 1
ds_filtered.apply_filter()
features = ds_filtered.features
if "inert_ratio_prnc" in features:
    features.remove('inert_ratio_prnc')
ds_filtered.export.hdf5(path='events_false_principal_inertia_ratio.rtdc', features=features, filtered=True, override=True)

with h5py.File('events_false_principal_inertia_ratio.rtdc', mode="r+") as h:
    for i in range(len(h['events']['pos_x'])):
        h['events']['pos_x'][i] = h['events']['pos_x'][i] - 200

ds_reduced_position = dclab.new_dataset("events_false_principal_inertia_ratio.rtdc")
plt.figure()
plt.plot(ds_reduced_position["pos_x"], ds_reduced_position["inert_ratio_prnc"], ".")
plt.ylim([0, 1])
```

**Comment by SaraKaliman** [comment]
I will assume dclab and dcevent have the same code for prnc calculation:

orient = 0.5 * np.arctan2(2 * mu_raw['mu11'],
                              mu_raw['mu02'] - mu_raw['mu20'])
    cc = np.array(cont_raw, dtype=np.float32, copy=True)  # float32 [sic]
    rho = np.sqrt(cc[:, 0] ** 2 + cc[:, 1] ** 2)
    phi = np.arctan2(cc[:, 1], cc[:, 0]) + orient + np.pi / 2
    cc[:, 0] = rho * np.cos(phi)
    cc[:, 1] = rho * np.sin(phi)
    # compute inertia ratio of rotated contour
    mprnc = cv2.moments(cc)
    root_prnc = mprnc["mu20"] / mprnc["mu02"]

The first problem is that orientation angle is calculated wrongly because arctan2 function should take
_np.arctan2(2 * -mu_raw['mu11'], mu_raw['mu20'] - mu_raw['mu02'])_
The nominator and denominator have wrong sign which than makes arctan2 place the angle in the wrong quartal. 
This error was present in the paper with Maik Herbig and probably propagates since then.

Secondly, principal components of the moment of inertia can be easily calculated by diagonalising the central moments matrix. Therefore, there is no need to rotate whole contour and recalculate the moments.
In dcevent: 
I will implement new version of the tilt and prnc calculation in dcevent together with whole new set of features that we can be added to the analysis. I plan to have this ready by the time we finish the new segmentation model so that both are implemented at the same time.
In dclab:
When it comes to correcting this bug in dclab, simply replacing  
_np.arctan2(2 * mu_raw['mu11'], mu_raw['mu02'] - mu_raw['mu20'])_
with 
_np.arctan2(2 * -mu_raw['mu11'], mu_raw['mu20'] - mu_raw['mu02'])_

should correct the problem.

**Comment by paulmueller** [comment]
Thanks for the thorough investigation :heart: 

Ar you planning to create a PR to fix this or should I take over from here?

**Comment by B-Hartmann** [comment]
I think it would be easier and faster if you would update the code, @paulmueller.

**Comment by SaraKaliman** [comment]
Yes, Paul maybe you could take over from here. Glad that I could help.

**Comment by paulmueller** [comment]
No, this is not the culprit.

Before flipping the sign:
![image](https://user-images.githubusercontent.com/2853022/225320485-b1d657a3-51cf-4a13-ae2f-ab70ff6ebb72.png)


After flipping the sign:
![image](https://user-images.githubusercontent.com/2853022/225320807-4d7c7e39-0124-47fb-bf73-d425fcda219f.png)

**Comment by paulmueller** [comment]
BTW this also affected the computation of the other inertia ratios as well as tilt.

**Comment by paulmueller** [comment]
![image](https://user-images.githubusercontent.com/2853022/225444627-98430bc9-95bc-476a-8432-1b4dda193a78.png)

Only tilt differs, because tilt is defined as strictly positive in dclab:
![image](https://user-images.githubusercontent.com/2853022/225444770-89cff54d-779e-4ff1-8aff-1ad758623454.png)

![image](https://user-images.githubusercontent.com/2853022/225444818-542c750a-7ce0-43cb-aba5-977b65cbc51f.png)

![image](https://user-images.githubusercontent.com/2853022/225444887-c5785367-4563-4063-861b-b3cccf76d4a2.png)

![image](https://user-images.githubusercontent.com/2853022/225444936-6a30ceeb-9943-494b-93aa-a30206e160ca.png)

**Comment by paulmueller** [comment]
Note that our (super private :no_mouth:) dcevent is not affected by this bug, since it is using the OpenCV implementation of moments all-the-way-through which does not use `int32` for contours.
